In [1]:
import numpy as np
from ipywidgets import IntSlider, HTMLMath

import plotlymath as pm
from myutils import interact, latex
colors = pm.plotly.colors.DEFAULT_PLOTLY_COLORS

# Example 1: War and Peace

## Order of the states: 

$P$ - Peace

$N$ - Neutral

$W$ - War


In [2]:
M = np.array([
    [0.30, 0.20, 0   ], 
    [0.60, 0.50, 0.50], 
    [0.10, 0.30, 0.50], 
])

In [4]:
label = latex((r"\text{Peace}", r"\text{Neutral}", r"\text{War}"))

initial_state = np.array((0, 0, 1), dtype=float)
state_list = [initial_state]
for t in range(100):
    state_list.append(M @ state_list[-1])
state_list = np.insert(state_list, 0, np.arange(101), axis=1)

figure, plot = pm.make_figure(widget=True)
plot._subplot.xaxis.domain = [0, 0.7]
plot.axes_ranges((0, 20), (0, 1))

@interact(t=IntSlider(min=0, max=100, value=0, description="$t$"))
def update(t):
    text = fr"${label} = {latex(state_list[t,1:], round=3)}$"
    with figure.batch_update():
        plot.text(text, (0.8, 0.5), paper=True, id="label")
        plot.points(state_list[:t+1,(0,1)], name="Peace", id="Peace", 
                mode="markers+lines", line_color="lightgray", marker_color="green")
        plot.points(state_list[:t+1,(0,2)], name="Neutral", id="Neutral", 
                mode="markers+lines", line_color="lightgray", marker_color="gray")
        plot.points(state_list[:t+1,(0,3)], name="War", id="War", 
                mode="markers+lines", line_color="lightgray", marker_color="red")

figure


interactive(children=(IntSlider(value=0, description='$t$'), Output()), _dom_classes=('widget-interact',))

FigureWidget({
    'data': [{'line': {'color': 'lightgray'},
              'marker': {'color': 'green', 'size'…

In [5]:
figure, plot = pm.make_figure(widget=True)
plot._subplot.xaxis.domain = [0, 0.7]
plot.axes_ranges((0, 20), (0, 1))
figure.layout.update(barmode="stack")

@interact(t=IntSlider(min=0, max=100, value=0, description="$t$"))
def update(t):
    text = fr"${label} = {latex(state_list[t,1:], round=3)}$"
    with figure.batch_update():
        plot.text(text, (0.8, 0.5), paper=True, id="label")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,1], name="Peace", id="Peace", 
                marker_color="green")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,2], name="Neutral", id="Neutral", 
                marker_color="lightgray")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,3], name="War", id="War", 
                marker_color="red")

figure


interactive(children=(IntSlider(value=0, description='$t$'), Output()), _dom_classes=('widget-interact',))

FigureWidget({
    'data': [{'marker': {'color': 'green'},
              'name': 'Peace',
              'type'…

In [6]:
evalues, T = np.linalg.eig(M)
evalues

array([ 1.        ,  0.35615528, -0.05615528])

In [7]:
T[:,0] / sum(T[:,0])

array([0.14705882, 0.51470588, 0.33823529])

In [8]:
np.linalg.matrix_power(M, 1000)

array([[0.14705882, 0.14705882, 0.14705882],
       [0.51470588, 0.51470588, 0.51470588],
       [0.33823529, 0.33823529, 0.33823529]])

In [9]:
HTMLMath(latex(np.linalg.matrix_power(M, 1000), round=4))

HTMLMath(value='\\begin{pmatrix} 0.1471 & 0.1471 & 0.1471 \\\\ 0.5147 & 0.5147 & 0.5147 \\\\ 0.3382 & 0.3382 &…

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>


# Example 2: Markov-ian squirrels in the UK
(from the textbook)

## States: 

$R$ - This area has only red squirrels

$G$ - This area has only gray squirrels

$B$ - This area has both species of squirrels

$O$ - This area has neither species of squirrels


In [10]:
M = np.array([
    [0.8797, 0.0382, 0.0527, 0.0008], 
    [0.0212, 0.8002, 0.0041, 0.0143], 
    [0.0981, 0.0273, 0.8802, 0.0527], 
    [0.0010, 0.1343, 0.0630, 0.9322], 
])

In [11]:
label = latex((r"\text{Red}", r"\text{Gray}", r"\text{Both}", r"\text{Neither}"))

initial_state = np.array((0.7, 0, 0, 0.3), dtype=float)
state_list = [initial_state]
for t in range(100):
    state_list.append(M @ state_list[-1])
state_list = np.insert(state_list, 0, np.arange(101), axis=1)

figure, plot = pm.make_figure(widget=True)
plot._subplot.xaxis.domain = [0, 0.7]
plot.axes_ranges((0, 20), (0, 1))

@interact(t=IntSlider(min=0, max=100, value=0, description="$t$"))
def update(t):
    text = fr"${label} = {latex(state_list[t,1:], round=3)}$"
    with figure.batch_update():
        plot.text(text, (0.8, 0.5), paper=True, id="label")
        plot.points(state_list[:t+1,(0,1)], name="Red only", id="Red", 
                mode="markers+lines", line_color="lightgray", marker_color="red")
        plot.points(state_list[:t+1,(0,2)], name="Gray only", id="Gray", 
                mode="markers+lines", line_color="lightgray", marker_color="gray")
        plot.points(state_list[:t+1,(0,3)], name="Both species", id="Both", 
                mode="markers+lines", line_color="lightgray", marker_color="green")
        plot.points(state_list[:t+1,(0,4)], name="Neither species", id="Neither", 
                mode="markers+lines", line_color="lightgray", marker_color="black")

figure

interactive(children=(IntSlider(value=0, description='$t$'), Output()), _dom_classes=('widget-interact',))

FigureWidget({
    'data': [{'line': {'color': 'lightgray'},
              'marker': {'color': 'red', 'size': …

In [12]:
figure, plot = pm.make_figure(widget=True)
plot._subplot.xaxis.domain = [0, 0.7]
plot.axes_ranges((0, 20), (0, 1))
figure.layout.update(barmode="stack")

@interact(t=IntSlider(min=0, max=100, value=0, description="$t$"))
def update(t):
    text = fr"${label} = {latex(state_list[t,1:], round=3)}$"
    with figure.batch_update():
        plot.text(text, (0.8, 0.5), paper=True, id="label")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,1], name="Red only", 
                id="Red", marker_color="red")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,2], name="Gray only", 
                id="Gray", marker_color="gray")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,3], name="Both species", 
                id="Both", marker_color="green")
        plot.Bar(x=state_list[:t+1,0], y=state_list[:t+1,4], name="Neither species", 
                id="Neither", marker_color="black")

figure


interactive(children=(IntSlider(value=0, description='$t$'), Output()), _dom_classes=('widget-interact',))

FigureWidget({
    'data': [{'marker': {'color': 'red'},
              'name': 'Red only',
              'type…

In [13]:
evalues, T = np.linalg.eig(M)
evalues

array([1.        , 0.90827656, 0.76882086, 0.81520258])

In [14]:
stationary = T[:,0]
stationary /= sum(stationary)
stationary

array([0.17053042, 0.05598683, 0.34214502, 0.43133773])

In [15]:
HTMLMath(latex(np.linalg.matrix_power(M, 1000), round=4))

HTMLMath(value='\\begin{pmatrix} 0.1705 & 0.1705 & 0.1705 & 0.1705 \\\\ 0.056 & 0.056 & 0.056 & 0.056 \\\\ 0.3…

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>


# Example 3: Coin-toss battle (with absorbing states)

## States: 

$Start$ - Start of the game, before any coin-toss

$W_1$ - You won the most recent 1 coin-toss, but not the one before that

$L_1$ - You lost the most recent 1 coin-toss, but not the one before that

$W_2$ - You won the most recent 2 coin-tosses, but haven't won the game

$L_2$ - You lost the most recent 2 coin-tosses, but haven't lost the game

$Win$ - You've won the game (won three coin-tosses in a row)

$Lose$ - You've lost the game (lost three coin-tosses in a row)


In [16]:
M = np.array([
    [0  , 0  , 0  , 0  , 0  , 0  , 0  ], # Start
    [0.5, 0  , 0.5, 0  , 0.5, 0  , 0  ], # Won 1 round
    [0.5, 0.5, 0  , 0.5, 0  , 0  , 0  ], # Lost 1 round
    [0  , 0.5, 0  , 0  , 0  , 0  , 0  ], # Won 2 rounds
    [0  , 0  , 0.5, 0  , 0  , 0  , 0  ], # Lost 2 rounds
    [0  , 0  , 0  , 0.5, 0  , 1  , 0  ], # Won the game
    [0  , 0  , 0  , 0  , 0.5, 0  , 1  ], # Lost the game
])
HTMLMath(latex(M))

HTMLMath(value='\\begin{pmatrix} 0 & 0 & 0 & 0 & 0 & 0 & 0 \\\\ 0.5 & 0 & 0.5 & 0 & 0.5 & 0 & 0 \\\\ 0.5 & 0.5…

<br>
<br>
<br>
<br>
<br>

### Raising the matrix $M$ to a high power: 

$$ \lim_{t \to \infty} M^t $$


In [17]:
HTMLMath(latex(np.linalg.matrix_power(M, 1000), round=4))

HTMLMath(value='\\begin{pmatrix} 0 & 0 & 0 & 0 & 0 & 0 & 0 \\\\ 0 & 0 & 0 & 0 & 0 & 0 & 0 \\\\ 0 & 0 & 0 & 0 &…

<br>
<br>
<br>
<br>
<br>

### That same result, computed using our new results: 

$$ \lim_{t \to \infty} M^t = \begin{pmatrix} 0 & 0 \\ BF & I \end{pmatrix} $$

where $F = (I - A)^{-1}$. 

In [18]:
A = M[:5,:5]
HTMLMath(f"$A = {latex(A)}$")

HTMLMath(value='$A = \\begin{pmatrix} 0 & 0 & 0 & 0 & 0 \\\\ 0.5 & 0 & 0.5 & 0 & 0.5 \\\\ 0.5 & 0.5 & 0 & 0.5 …

In [19]:
B = M[5:,:5]
HTMLMath(f"$B = {latex(B)}$")

HTMLMath(value='$B = \\begin{pmatrix} 0 & 0 & 0 & 0.5 & 0 \\\\ 0 & 0 & 0 & 0 & 0.5 \\end{pmatrix}$')

In [20]:
F = np.linalg.inv(np.eye(5) - A)
HTMLMath(f"$F = {latex(F, round=4)}$")

HTMLMath(value='$F = \\begin{pmatrix} 1 & 0 & 0 & 0 & 0 \\\\ 2 & 2.2857 & 1.7143 & 0.8571 & 1.1429 \\\\ 2 & 1.…

In [21]:
HTMLMath(f"$BF = {latex(B @ F, round=4)}$")

HTMLMath(value='$BF = \\begin{pmatrix} 0.5 & 0.5714 & 0.4286 & 0.7143 & 0.2857 \\\\ 0.5 & 0.4286 & 0.5714 & 0.…

In [22]:
HTMLMath(latex(np.linalg.matrix_power(M, 1000)[5:,:5], round=4))

HTMLMath(value='\\begin{pmatrix} 0.5 & 0.5714 & 0.4286 & 0.7143 & 0.2857 \\\\ 0.5 & 0.4286 & 0.5714 & 0.2857 &…

<br>
<br>
<br>
<br>
<br>

### Simulating the game


In [23]:
def simulate():
    turns = 0
    # wins counts the number of consecutive wins (positive) or losses (negative)
    # So wins ==  0 means (Start)
    # So wins ==  1 means (W1)
    # So wins == -1 means (L1)
    # So wins ==  2 means (W2)
    # So wins == -2 means (L2)
    # So wins ==  3 means (Win)
    # So wins == -3 means (Lose)
    wins = 0
    while abs(wins) < 3:
        # toss is 1 if we won that round, -1 if we lost that round
        toss = np.random.randint(0, 2) * 2 - 1
        #print("W" if toss == 1 else "L")
        wins = toss if wins * toss <= 0 else wins + toss
        turns += 1
    return bool(wins > 0), turns


In [24]:
# Run many simulations, and collect the number of turns for each simulation into an array
results = np.zeros((10000,), dtype=int)
for i in range(10000):
    win, turns = simulate()
    results[i] = turns

# Compute the average number of turns required
results.mean()

7.044

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
